title: JDME
description: Sitio académico

url: "https://dariomics.github.io"
baseurl: ""

markdown: kramdown
theme: minima

header_pages:
  - service-social/index.md
  - estudiantes.md
  - egresados.md
  - publicaciones.md
  - divulgacion.md
  - simposio.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
